config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :users do
    resources :coffee_beans, shallow: true
  end

  resources :recipes
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/coffee_bean.rb
class CoffeeBean < ActiveRecord::Base
  has_many :recipes, dependent: :destroy
  belongs_to :user

  validates :name, :brand, :roast, presence: true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  belongs_to :coffee_bean

  validates :coffee_bean, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes
  has_many :coffee_beans

  validates :email, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= session[:current_user_id] && User.find_by(id: session[:current_user_id])
  end

  helper_method :current_user
end

app/controllers/coffee_beans_controller.rb
class CoffeeBeansController < ApplicationController
  def new
    @coffee = CoffeeBean.new
  end

  def create
    @user = User.find(params[:user_id])
    @coffee = @user.coffee_beans.new(coffee_params)
    if @coffee.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
    @coffee = CoffeeBean.find(params[:id])
  end

  def update
    @user = current_user
    @coffee = CoffeeBean.find(params[:id])
    if @coffee.update_attributes(coffee_params)
      redirect_to user_coffee_beans_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @coffee = CoffeeBean.find(params[:id])
    @coffee.destroy
    redirect_to user_coffee_beans_path(current_user)
  end

  def index
    @user = User.find(params[:user_id])
    @coffees = @user.coffee_beans.all
  end

  def show
    @coffee = CoffeeBean.find(params[:id])
  end

  private
  def coffee_params
    params.require(:coffee_bean).permit(:brand, :roast, :name, :origin, :description_short)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    search = params[:search]
    if search
      @recipes = Recipe.where('description LIKE ? OR title LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%").order(created_at: :desc)
    else
      @recipes = Recipe.all.order(created_at: :desc)
    end

    if current_user
      @recipe = current_user.recipes.build
      @coffee = CoffeeBean.where('user_id = ?', current_user)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = User.find(@recipe.user_id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    user = User.find(current_user.id)
    @recipe = user.recipes.new(recipe_params)
    @coffee = CoffeeBean.where('user_id = ?', current_user)

    if @recipe.save
      redirect_to :recipes
    else
      render :new
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
    @coffee = CoffeeBean.where('user_id = ?', current_user)
  end

  def update
    @recipe = current_user.recipes.find(params[:id])
    @recipe.update_attributes(recipe_params)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to user_path(current_user)
  end

  private
  def recipe_params
    params.require(:recipe).permit(:user_id, :water_vol, :water_temp, :title, :technique, :description, :coffee_bean_id, :coffee_amount)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end

  end

  def destroy
    session[:current_user_id] = nil
    redirect_to recipes_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @recipes = @user.recipes.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_beans_helper.rb
module CoffeeBeansHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coffee_beans/_coffee.html.erb
<div class="coffee-bean">
  <div class="coffee-description">
    <div class="coffee-name"><h3><%= coffee.name %></h3></div>
    <div class="coffee-brand">Brand: <%= coffee.brand %></div>
    <div class="coffee-roast">Roast: <%= coffee.roast %></div>
    <div class="coffee-origin">Origin: <%= coffee.origin %></div>
    <div class="coffee-origin">Description: <%= coffee.description_short %></div>
  </div>
</div>

<%= link_to "edit", edit_coffee_bean_path(coffee) %>
<%= link_to 'Destroy', coffee_bean_path(coffee), method: :delete,data: { confirm: 'Are you sure?' } %>

app/views/coffee_beans/_coffee_form.html.erb
<%= form_for coffee do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :brand %>
    <%= f.text_field :brand, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :origin %>
    <%= f.text_field :origin, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :roast %>
    <%= f.text_field :roast, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description_short %>
    <%= f.text_field :description_short, class: "form-control" %>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
<% end %>

<%= render partial:'shared/error_messages', locals: {object: coffee} %>

app/views/coffee_beans/create.html.erb
<h1>CoffeeBeans#create</h1>
<p>Find me in app/views/coffee_beans/create.html.erb</p>

app/views/coffee_beans/destroy.html.erb
<h1>CoffeeBeans#destroy</h1>
<p>Find me in app/views/coffee_beans/destroy.html.erb</p>

app/views/coffee_beans/edit.html.erb
<h1>Edit</h1>

<%= render partial: 'coffee_form', locals: {coffee: @coffee, user: current_user} %>
<%= link_to "Cancel", :back, class: "btn btn-default form-cancel-button" %>

app/views/coffee_beans/index.html.erb
<h1>Coffees</h1>

<% if current_user %>
  <%= link_to "Add coffee", new_user_coffee_bean_path(current_user), class: "btn btn-default" %>
<% end %>

<% @coffees.each do |coffee| %>
  <%= render partial: 'coffee', locals: {coffee: coffee} %>
<% end %>

app/views/coffee_beans/new.html.erb
<h1>CoffeeBeans#new</h1>

<%= render partial: 'coffee_form', locals: {coffee: @coffee, user: current_user} %>

app/views/coffee_beans/show.html.erb
<%= render partial: 'coffee', locals: {coffee: @coffee} %>

app/views/coffee_beans/update.html.erb
<h1>CoffeeBeans#update</h1>
<p>Find me in app/views/coffee_beans/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoffeeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Coffee Recipes", recipes_path, class: "navbar-brand" %>
    </div>
    <div class="user-menu navbar-right">
      <% if current_user %>
        <button type="button" class="btn btn-default">
          <%= link_to current_user.name, user_path(current_user) %>
          <span class="glyphicon glyphicon-user"></span>
        </button>
        <button type="button" class="btn btn-default navbar-btn">
          <%= link_to "Log out", session_path("current"), :method => :delete %>
        </button>
      <% else %>
        <button type="button" class="btn btn-default navbar-btn"><%= link_to "Login", new_session_path %></button>
        <button type="button" class="btn btn-default navbar-btn"><%= link_to "Sign up", new_user_path %></button>
      <% end %>
    </div>
  </div>
</nav>

<div class="container content">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/recipes/_new_recipe_form.html.erb
<div class="form-container">

  <button class="btn btn-default" id="add-recipe"><%= link_to "Add recipe", new_recipe_path %></button>

  <%= form_for [@user, @recipe] do |f| %>
    <div class="form-horizontal col-sm-12" id="new-recipe-form">
    <button class="btn btn-default pull-right" id="close-new-recipe-form">
      <span class="glyphicon glyphicon-remove"></span>
    </button>
    <div class="form-group">
      <%= f.label :title, class: "col-sm-2 control-label"%>
      <div class="col-sm-6">
        <%= f.text_field :title, class: "form-control"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :water_vol, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :water_vol, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :coffee_amount, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :coffee_amount, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :water_temp, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :water_temp, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :technique, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_area :technique, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-6 col-sm-offset-2"><%= f.submit %></div>
    </div>
  </div>
  <% end %>
</div>

app/views/recipes/_recipe.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2><%= @recipe.title %></h2>
  </div>
    <div class="coffee_recipe panel-body">
      <div class="user-info">
        Created by <%= link_to @user.name, user_path(@user) %>
        <%= link_to 'edit', edit_recipe_path(@recipe) %>
      </div>
      <div class="panel panel-info">
        <div class="panel-heading"><h4>This recipe uses</h4></div>
        <div class="panel-body">
          Coffee: <%= link_to @recipe.coffee_bean.name, coffee_bean_path(@recipe.coffee_bean)  %>
        </div>
      </div>
      <p><%= @recipe.description %></p>
      <ul class="list-group">
        <li class="list-group-item"><strong>Water temperature:</strong> <%= @recipe.water_temp %> &#8451</li>
        <li class="list-group-item"><strong>Water volume:</strong> <%= @recipe.water_vol %> ml</li>
        <li class="list-group-item"><strong>Coffee amount:</strong> <%= @recipe.coffee_amount %> g</li>
      </ul>
      <div class="recipe-technique">
        <h4>Recipe Technique</h4>
        <p><%= @recipe.technique %></p>
      </div>
   </div>
  </div>
</div>

app/views/recipes/_recipe_form.html.erb
<%= form_for [@user, @recipe], html: {class: "form-horizontal"} do |f| %>
    <div class="form-group">
      <%= f.label :title, class: "col-sm-2 control-label"%>
      <div class="col-sm-6">
        <%= f.text_field :title, class: "form-control"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>

     <div class="form-group">
      <div class="col-sm-6 col-sm-offset-2">
        <%= f.collection_select(:coffee_bean_id, @coffee, :id, :name, {prompt: "Choose Coffee"}, {class: "form-control"})  %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :water_vol, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :water_vol, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :coffee_amount, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :coffee_amount, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :water_temp, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :water_temp, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :technique, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_area :technique, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-6 col-sm-offset-2">
        <button type="submit" class="btn btn-default">Save</button>
      </div>
    </div>
<% end %>

<%= render partial: "shared/error_messages", locals: {object: @recipe} %>

app/views/recipes/edit.html.erb
<h1>Edit</h1>
<%= render 'recipe_form' %>
<%= link_to "Delete", recipe_path(@recipe), method: :delete, class: "btn btn-default", data: { confirm: "Delete Item?" } %>

app/views/recipes/index.html.erb
<div class="jumbotron recipes-header">
  <h1>Brewing Coffee</h1>
  <p>Share your brewing techniques</p>
</div>

<div class="search-form">
  <%= form_tag recipes_path, method: "get", class: "form-inline" do %>
    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "by title or description"%>
     <button type="submit" class="btn btn-default">Search</button>
  <% end %>
</div>

<% if current_user %>
  <div class="form-container">
    <button class="btn btn-default" id="add-recipe"><%= link_to "Add recipe", new_recipe_path %></button>
    <div id="hide-form" class="col-sm-12">
      <button class="btn btn-default pull-right" id="close-new-recipe-form">
        <span class="glyphicon glyphicon-remove"></span>
      </button>
      <%= render 'recipe_form' %>
    </div>
  </div>
<% end %>

<% @recipes.each do |recipe| %>
  <div class="coffee_recipe list-group-item">
    <h3 class="list-group-heading"><%= link_to recipe.title, recipe_path(recipe) %></h3>
    <p class="description list-group-item-text"><%= recipe.description %><p>
  </div>
<% end %>

app/views/recipes/new.html.erb
<%= render 'recipe_form' %>

app/views/recipes/show.html.erb
<%= render 'recipe' %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>New User Signup</h1>


<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>
<%= render partial: "shared/error_messages", locals: {object: @user} %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>
<p>Email: <%= @user.email %><p>

<nav>
  <%= link_to "coffees", user_coffee_beans_path(@user) %>
</nav>

<h3>Recipes</h3>
<div class="user-recipes">
  <ul class="list-group">
  <% @recipes.each do |recipe| %>
    <li class="list-group-item"><%= link_to recipe.title, recipe_path(recipe) %></li>
  <% end %>
  </ul>
</div>